### ISSUE TITLE
FYI: Bit 31 not fully tested

### ISSUE THREAD

**Issue by jcw** [PaulStoffregen/teensy41_psram_memtest#2]
https://github.com/PaulStoffregen/teensy41_psram_memtest/blob/7649a10619937fae5c3bf76fa28f5e684b84e985/teensy41_psram_memtest.ino#L119-L124

The "fixed" tests _will_ correctly exercise bit 31, but the way the above code is written, it will always stay zero here.

**Comment by PaulStoffregen** [comment]
opps, yes, you're right this is only a 31 bit LFSR
